steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pinger', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pinger']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'pinger', '--image', 'gcr.io/$PROJECT_ID/pinger', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/pinger